name: Build (Android-Public)

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true

jobs:
  android:
    name: ${{ matrix.platform.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nttld/setup-ndk@v1
        id: setup_ndk
        with:
          ndk-version: r21e
      - name: Build (Android.mk)
        run: |
          ./build-scripts/androidbuildlibs.sh
      - uses: actions/upload-artifact@master
        with:
          name: SDL2-${{ github.sha }}
          path: ./build/android/**/*
